### ISSUE TITLE
Out of date documentation

### ISSUE THREAD

**Issue by p0pr0ck5** [Kusumoto/docker-openresty#1]
Hi,

The synopsis provided for lua-resty-waf is out of date, particularly in that `exec` is not called in `log_by_lua` (we have allowed this since https://github.com/p0pr0ck5/lua-resty-waf/commit/22f1b1cab909ca775c61178b0d897629c243468e). Please consider updating your docs, or just linking to our Readme so there's no versioning conflict. Thanks :)

**Comment by Kusumoto** [comment]
Hi.

Thank you for this report. I already update readme file in #2
